services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: rentify-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Rentify@123456"
    ports:
      - "1433:1433"
    volumes:
      - rentify-sql-data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "Rentify@123456" -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

volumes:
  rentify-sql-data:
